services:
  - type: web
    name: kitabistan-cart
    rootDir: cart-service
    runtime: docker
    envVars:
      - key: DATABASE_PATH
        value: /app/db/cart.db
    disk:
      name: cart-data
      mountPath: /app/db
      sizeGB: 1

  - type: web
    name: kitabistan-product
    rootDir: product-service
    runtime: docker
    envVars:
      - key: DATABASE_PATH
        value: /app/db/product.db
    disk:
      name: product-data
      mountPath: /app/db
      sizeGB: 1

  - type: web
    name: kitabistan-order
    rootDir: order-service
    runtime: docker
    envVars:
      - key: DATABASE_PATH
        value: /app/db/order.db
      - key: PRODUCT_SERVICE_URL
        value: https://kitabistan-product.onrender.com
    disk:
      name: order-data
      mountPath: /app/db
      sizeGB: 1

  - type: web
    name: kitabistan-payment
    rootDir: payment-service
    runtime: docker
    envVars:
      - key: DATABASE_PATH
        value: /app/db/payment.db
      - key: ORDER_SERVICE_URL
        value: https://kitabistan-order.onrender.com
      - key: PRODUCT_SERVICE_URL
        value: https://kitabistan-product.onrender.com
    disk:
      name: payment-data
      mountPath: /app/db
      sizeGB: 1